const comparison_plots = [
    "helmert_F1I_F1.png",
    "helmert_F1I_F1.png",
    "crd_comparison.png",
    "helmert_F1I_F1.png",
    "crd_comparison.png",
    "pre_comparison.png",
    "pre_comparison.png",
    "erp_comparison.png",
    "pre_comparison.png",
    "erp_comparison.png",
    "std_comparison.png",
];
    "std_comparison.png",
    "helmert_F1I_F1.png",
    "std_comparison.png",
    "helmert_F1I_F1.png",
];
];
    "pre_comparison.png",
    "pre_comparison.png",
    "std_comparison.png",
];
    "std_comparison.png",
];
