const latest_plots = [
    "gpsxtr_par.png",
    "large_obs_files.png",
    "amb_stats.png",
    "gpsxtr_rms.png",
    "num_obs_files.png",
    "clock_completeness_heatmap.png",
    "large_obs_files.png",
    "obsxtr_bad.png",
];
    "gpsxtr_obs.png",
    "num_obs_files.png",
    "gpsxtr_par.png",
    "obsxtr_bad.png",
];
    "gpsxtr_rms.png",
    "large_obs_files.png",
    "num_obs_files.png",
    "obsxtr_bad.png",
];
