const ppp_plots = [
    "ROTH_plot.png",
    "ROTH_plot.png",
    "ROTH_plot.png",
    "CPVG_plot.png",
    "CPVG_plot.png",
    "SCOR_plot.png",
    "SCOR_plot.png",
    "SCOR_plot.png",
    "ROTH_plot.png",
    "ROTH_plot.png",
    "WGTN_plot.png",
    "WGTN_plot.png",
    "WGTN_plot.png",
    "SCOR_plot.png",
    "SCOR_plot.png",
    "ZIM3_plot.png",
];
    "ZIM3_plot.png",
];
    "WGTN_plot.png",
    "ZIM3_plot.png",
];
    "WGTN_plot.png",
    "ZIM3_plot.png",
];
    "ZIM3_plot.png",
];
